### ISSUE TITLE
Little advice on CDN usage

### ISSUE THREAD

**Issue by CrazyFluffyPony** [Levyks/stormworks-path-drawer#1]
Hey there,
cool to see someone building awesome tools for others. Keep it up!
Pony

---
Regarding https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css

CDNs (like you use, knowningly or not) are nice to have for big websites with tons of resources to be loaded (because of increase of parallel HTTP connections, smaller reaction time due to closer server, ...).

In your case, you only have a handful of resources. You almost only have disadvantages when using a CDN resource with this setup:
* resource missing when offline
* third party included
* external dependency (might become invalid, unreachable at some point in future)
* causes your computer to start a DNS lookup (which most definitely will take longer then the whole transmission of the file *from your machine to your machine*

In case you need a second domain or fake CDN or fully qualified domain name that resolves to your local machine (127.0.0.1 or localhost) you can use lvh.me (They have ) http://lvh.me:3000/

**Comment by Levyks** [comment]
@CrazyFluffyPony, I'm a huge fan of your work, your Lua IDE is so useful, i use it in basically all of my Stormworks's projects.

About the CDN, I did that in a hurry, I fixed it now so that the .css file is self-hosted and not sourced from a CDN anymore, thanks for the tip.
